# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: 建立NET环境
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: 安装依赖包
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: 添加nuget仓库
      run: nuget sources add -name github -Source https://nuget.pkg.github.com/ORGANIZATION_NAME/index.json -Username ORGANIZATION_NAME -Password ${{ secrets.GitHubPushPackageKey }}
    - name: 安装nuget
      uses: nuget/setup-nuget@v1
    - name: 推送nuget包
      run: nuget push ./ElasticSearchDSL.Core/bin/Release/*.nupkg -Source https://api.nuget.org/v3/index.json -SkipDuplicate -ApiKey ${{ secrets.NugetKey }} -NoSymbol
